[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**/*.js"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173
  port = 3008
  functionsPort = 3009

[build.environment]
  NODE_VERSION = "20.11.1"
  NPM_VERSION = "10.2.3"
  VITE_API_URL = "/.netlify/functions/api"