[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ytdl-core", "tiktok-scraper"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173
  port = 3008
  functionsPort = 3009

[build.environment]
  NODE_VERSION = "18.0.0"
  NPM_VERSION = "9.5.0"
  VITE_API_URL = "/.netlify/functions/api"