[build]
  command = "git clone --depth 1 --no-checkout https://github.com/solo89895/video-downloader-frontend && cd video-downloader-frontend && npm install && npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 